
version: "3.9"


services:
  
  repo:
    image: repo
    
    volumes:
      - ./repo:/repo2

    command: 
      - bash 
      - -c 
      - |
        rm -rf /repo2/*
        cp -r /repo/* /repo2
        sleep infinity

  local:
    image: local
    
    volumes:
      - ./repo:/repo

    command: 
      - bash 
      - -c 
      - |
        sleep infinity
